---
title: "Correlates and Policy Remedies of DC's Urban Heat Island Effect"
author: "Evan Bowman"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  pdf_document: default
  html_document: default
  word_document: default
bibliography: Memo.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Introduction

A major discussion in today's politics is the consequences of climate change and what is to come if no meaningful attempt at mitigating atmospheric greenhouse gasses occurs. These consequences, on a meta level, range from higher mean temperatures, sea level rise, and changes in the ability to grow sustainable food. These potential consequences poses large public health risks such as increases in heat related deaths and illness. This is cause for concern as about 25 percent of natural hazard mortality in the country is caused by heat exposure [@benz2021widespread]. Furthermore, heat-related mortality in the USA causes roughly 1,500 more deaths annually than other severe weather events, as well as other outcomes such as heat strokes, dehydration, loss of labor productivity, and decreased learning [@hsu2021disproportionate]. The potential increase in heat related health incidents requires a substantial need for policy to combat increases in mean temperatures. 

Little discussion looks at the discrepancies these effects might have on urban populations. On the topic of increased global temperature averages, there is a need to look at the intersectionality of an already occurring phenomenon: urban heat island effects. This concept revolves around the key fact that urbanized city centers already create higher mean temperatures compared to their rural counterparts. Not only are these urban centers more likely to have higher mean temperatures than rural areas, there are clear sociodemographic discrepancies between populations within these cities. Few studies have been published analyzing these demographic discrepancies. However, in one report, research has found that roughly 77 percent of counties studied show that there are large differences in change of daytime temperature between census tracts with the highest and lowest Black population proportions. Furthermore, 81 percent of counties studied with lower difference in daytime temperature are majority non-Hispanic White. [@benz2021widespread]. There is also empirical evidence that shows discrepancies in urban heat island effects targeting communities that are more impoverished. For example, a 2020 study found that there is a negative correlation of .88 between cities' urban heat island effects and income [@chakraborty2020spatially]. This is further cause for concern when looking at potential correlations between poverty and race in city census tracts. 

These findings are consistent with research that shows majority minority populations in urban centers have less tree cover and larger proportions of impervious surfaces than majority non-Hispanic White populations. This shows a clear need for social policy that protects majority minority census tracts from being disproportionately affected by increased heat island effects. Research regarding the effects of urban heat island effects must be on a local level to adequately identify meaningful social demographic trends for areas within urban centers. These could be specific neighborhoods, districts, census tracts, etc. In the context of racial inequities in Washington DC, most research is done at the ward level. For this study, census tracts are chosen as sample observations to be able to identify which specific areas of DC's eight wards are most at risk of the urban heat island effect, and the demographic patterns that coincide with these risks.

\newpage
# **References**

